<?php

namespace App\Mainframe\Modules\Groups\Traits;

use App\Mainframe\Modules\Groups\GroupProcessor;

trait GroupProcessorTrait
{
    /*
       |--------------------------------------------------------------------------
       | Rules.
       |--------------------------------------------------------------------------
       |
       | Write the laravel validation rules
       */
    /**
     * Validation rules. For regular expression validation use array instead of pipe
     *
     * @param       $element
     * @param  array  $merge
     * @return array
     */
    public static function rules($element, $merge = [])
    {
        $rules = [
            'name' => 'required|between:1,255|unique:modules,name,'.(isset($element->id) ? (string) $element->id : 'null').',id,deleted_at,NULL',
            'is_active' => 'in:1,0',
        ];

        return array_merge($rules, $merge);
    }

    /*
   |--------------------------------------------------------------------------
   | Execute validation on module events
   |--------------------------------------------------------------------------
   |
   | Check validations on saving, creating, updating, deleting and restoring
   */
    /**
     * Run validations for saving. This should be common for both creating and updating.
     *
     * @param $element \App\Group
     * @return $this
     */
    public function saving($element)
    {
        $permissions = [];
        // revoke existing group permissions
        $existing_permissions = $element->getPermissions();
        if (count($existing_permissions)) {
            foreach ($existing_permissions as $k => $v) {
                $permissions[$k] = 0;
            }
        }

        // include new group permissions from form input
        foreach (request('permission', []) as $k) {
            $permissions[$k] = 1;
        }

        $element->permissions = array_merge($element->permissions, $permissions);

        return $this;
    }
    /**
     * Run validations for creating. This should always call the saving().
     *
     * @return \App\Mainframe\Features\Modular\Validator\ModelProcessor|\App\Mainframe\Modules\Settings\SettingProcessor
     */
    // public function creating()
    // {
    //     return parent::creating(); // TODO: Change the autogenerated stub
    // }

    /**
     * Run validations for updating. This should always call the saving().
     *
     * @return \App\Mainframe\Features\Modular\Validator\ModelProcessor|\App\Mainframe\Modules\Settings\SettingProcessor
     */
    // public function updating()
    // {
    //     return parent::updating(); // TODO: Change the autogenerated stub
    // }

    /**
     * Run validations for deleting.
     *
     * @return \App\Mainframe\Features\Modular\Validator\ModelProcessor|\App\Mainframe\Modules\Settings\SettingProcessor
     */
    // public function deleting()
    // {
    //     return parent::deleting(); // TODO: Change the autogenerated stub
    // }

    /**
     * Run validations for restoring. This should always call the saving().
     *
     * @return \App\Mainframe\Features\Modular\Validator\ModelProcessor|\App\Mainframe\Modules\Settings\SettingProcessor
     */
    // public function restoring()
    // {
    //     return parent::restoring(); // TODO: Change the autogenerated stub
    // }
}