<?php

namespace App\Mainframe\Modules\Notifications;

use App\Mainframe\Features\Modular\Validator\ModelProcessor;

class NotificationProcessor extends ModelProcessor
{
    /*
    |--------------------------------------------------------------------------
    | Fill model .
    |--------------------------------------------------------------------------
    |
    | Sometimes you need to automatically fill some fields of a model based
    | on known logic. For example: if you can take first_name and last_name
    | of an user and auto fill full_name.
    */

    /**
     * Fill the model with values
     *
     * @param  \App\Mainframe\Modules\Notifications\Notification  $notification
     * @return $this
     */
    public function fill($notification)
    {
        parent::fill($notification);

        // $notification->name = 'Lorem Ipsum';

        return $this;
    }

    /*
    |--------------------------------------------------------------------------
    | Rules.
    |--------------------------------------------------------------------------
    |
    | Write the laravel validation rules
    */

    /**
     * Validation rules.
     *
     * @param  \App\Mainframe\Modules\Notifications\Notification  $notification
     * @param  array  $merge
     * @return array
     */
    public static function rules($notification, $merge = [])
    {
        $rules = [
            'name' => 'required|between:1,255|unique:notifications,name,'.(isset($notification->id) ? (string) $notification->id : 'null').',id,deleted_at,NULL',
            'is_active' => 'in:1,0',
        ];

        return array_merge($rules, $merge);
    }

    /**
     * Custom error messages.
     *
     * @param  array  $merge
     * @return array
     */
    public static function customErrorMessages($merge = [])
    {
        $messages = [];

        return array_merge($messages, $merge);
    }

    /*
    |--------------------------------------------------------------------------
    | Execute validation on module events
    |--------------------------------------------------------------------------
    |
    | Check validations on saving, creating, updating, deleting and restoring
    */

    /**
     * Run validations for saving. This should be common for both creating and updating.
     *
     * @param $notification \App\Mainframe\Modules\Superheroes\Notification
     * @return $this
     */
    public function saving($notification)
    {
        parent::saving($notification);
        /*
        |--------------------------------------------------------------------------
        | Call validation functions one by one.
        |--------------------------------------------------------------------------
        |
        | A list of functions that will be called sequentially to validate the model
        */
        $this->nameIsNotJoker($notification);
        // $this->valueIsNotPrime($notification);
        // $this->hasEnoughGunsToFight($notification);
        // $this->heroIsNotInHospital($notification);

        return $this;
    }

    // /**
    //  * Creating validation
    //  *
    //  * @param $notification \App\Mainframe\Modules\Superheroes\Notification
    //  * @return \App\Mainframe\Features\Modular\Validator\ModelValidator|\App\Mainframe\Modules\Settings\SettingValidator
    //  */
    // public function creating($notification)
    // {
    //     return parent::creating($notification); // TODO: Change the autogenerated stub
    // }
    //
    // /**
    //  * Updating validation
    //  *
    //  * @param $notification \App\Mainframe\Modules\Superheroes\Notification
    //  * @return \App\Mainframe\Features\Modular\Validator\ModelValidator|\App\Mainframe\Modules\Settings\SettingValidator
    //  */
    // public function updating($notification)
    // {
    //     return parent::updating($notification); // TODO: Change the autogenerated stub
    // }
    //
    // /**
    //  *  Deleting validation
    //  *
    //  * @param $notification \App\Mainframe\Modules\Superheroes\Notification
    //  * @return \App\Mainframe\Features\Modular\Validator\ModelValidator|\App\Mainframe\Modules\Settings\SettingValidator
    //  */
    // public function deleting($notification)
    // {
    //     return parent::deleting($notification); // TODO: Change the autogenerated stub
    // }
    //
    // /**
    //  * Restoring validation
    //  *
    //  * @param $notification \App\Mainframe\Modules\Superheroes\Notification
    //  * @return \App\Mainframe\Features\Modular\Validator\ModelValidator|\App\Mainframe\Modules\Settings\SettingValidator
    //  */
    // public function restoring($notification)
    // {
    //     return parent::restoring($notification); // TODO: Change the autogenerated stub
    // }

    /*
    |--------------------------------------------------------------------------
    | Validation helper functions
    |--------------------------------------------------------------------------
    |
    | All validation must be checked through some function. All validation
    | functions are listed below.
    */

    /**
     * Validate the name. Name should not be 'Joker'
     *
     * @param $notification \App\Mainframe\Modules\Superheroes\Notification
     * @return $this
     */
    private function nameIsNotJoker($notification)
    {
        if ($notification->name === 'Joker') {
            $this->fieldError('name', "Name can not be Joker");
        }

        return $this;
    }
}