<?php

namespace App\Mainframe\Modules\Notifications\Traits;

use App\Mainframe\Modules\Notifications\Notification;

trait NotificationProcessorTrait
{

    /**
     * Fill the model with values
     *
     * @param  \App\Mainframe\Modules\Notifications\Notification  $notification
     * @return $this
     */
    public function fill($notification)
    {
        parent::fill($notification);

        // $notification->name = 'Lorem Ipsum';

        return $this;
    }

    /*
    |--------------------------------------------------------------------------
    | Rules.
    |--------------------------------------------------------------------------
    |
    | Write the laravel validation rules
    */

    /**
     * Validation rules.
     *
     * @param  \App\Mainframe\Modules\Notifications\Notification  $notification
     * @param  array  $merge
     * @return array
     */
    public static function rules($notification, $merge = [])
    {
        $rules = [
            // 'name' => 'required|between:1,255|unique:notifications,name,'.(isset($notification->id) ? (string) $notification->id : 'null').',id,deleted_at,NULL',
            'is_active' => 'in:1,0',
        ];

        return array_merge($rules, $merge);
    }

    /**
     * Custom error messages.
     *
     * @param  array  $merge
     * @return array
     */
    public static function customErrorMessages($merge = [])
    {
        $messages = [];

        return array_merge($messages, $merge);
    }

    /*
    |--------------------------------------------------------------------------
    | Execute validation on module events
    |--------------------------------------------------------------------------
    |
    | Check validations on saving, creating, updating, deleting and restoring
    */

    /**
     * Run validations for saving. This should be common for both creating and updating.
     *
     * @param  Notification  $notification
     * @return $this
     */
    public function saving($notification)
    {
        parent::saving($notification);

        return $this;
    }

    // /**
    //  * Creating validation
    //  *
    //  * @param $notification \App\Mainframe\Modules\Superheroes\Notification
    //  * @return \App\Mainframe\Features\Modular\Validator\ModelValidator|\App\Mainframe\Modules\Settings\SettingValidator
    //  */
    // public function creating($notification)
    // {
    //     return parent::creating($notification); // TODO: Change the autogenerated stub
    // }
    //
    // /**
    //  * Updating validation
    //  *
    //  * @param $notification \App\Mainframe\Modules\Superheroes\Notification
    //  * @return \App\Mainframe\Features\Modular\Validator\ModelValidator|\App\Mainframe\Modules\Settings\SettingValidator
    //  */
    // public function updating($notification)
    // {
    //     return parent::updating($notification); // TODO: Change the autogenerated stub
    // }
    //
    // /**
    //  *  Deleting validation
    //  *
    //  * @param $notification \App\Mainframe\Modules\Superheroes\Notification
    //  * @return \App\Mainframe\Features\Modular\Validator\ModelValidator|\App\Mainframe\Modules\Settings\SettingValidator
    //  */
    // public function deleting($notification)
    // {
    //     return parent::deleting($notification); // TODO: Change the autogenerated stub
    // }
    //
    // /**
    //  * Restoring validation
    //  *
    //  * @param $notification \App\Mainframe\Modules\Superheroes\Notification
    //  * @return \App\Mainframe\Features\Modular\Validator\ModelValidator|\App\Mainframe\Modules\Settings\SettingValidator
    //  */
    // public function restoring($notification)
    // {
    //     return parent::restoring($notification); // TODO: Change the autogenerated stub
    // }

    /*
    |--------------------------------------------------------------------------
    | Validation helper functions
    |--------------------------------------------------------------------------
    |
    | All validation must be checked through some function. All validation
    | functions are listed below.
    */

}