<?php

namespace App\Mainframe\Modules\Samples\LoremIpsums;

use App\Mainframe\Features\Modular\Validator\ModelProcessor;

class LoremIpsumProcessor extends ModelProcessor
{
    /*
    |--------------------------------------------------------------------------
    | Fill model .
    |--------------------------------------------------------------------------
    |
    | Sometimes you need to automatically fill some fields of a model based
    | on known logic. For example: if you can take first_name and last_name
    | of an user and auto fill full_name.
    */

    /**
     * Fill the model with values
     *
     * @param  \App\Mainframe\Modules\Samples\LoremIpsums\LoremIpsum  $loremIpsum
     * @return $this
     */
    public function fill($loremIpsum)
    {
        parent::fill($loremIpsum);

        // $loremIpsum->name = 'Lorem Ipsum';

        return $this;
    }

    /*
    |--------------------------------------------------------------------------
    | Rules.
    |--------------------------------------------------------------------------
    |
    | Write the laravel validation rules
    */

    /**
     * Validation rules.
     *
     * @param  \App\Mainframe\Modules\Samples\LoremIpsums\LoremIpsum  $loremIpsum
     * @param  array  $merge
     * @return array
     */
    public static function rules($loremIpsum, $merge = [])
    {
        $rules = [
            'name' => 'required|between:1,255|unique:lorem_ipsums,name,'.(isset($loremIpsum->id) ? (string) $loremIpsum->id : 'null').',id,deleted_at,NULL',
            'is_active' => 'in:1,0',
            // 'select_array' => 'required',
            // 'select_array_multiple' => 'required',
        ];

        return array_merge($rules, $merge);
    }

    /**
     * Custom error messages.
     *
     * @param  array  $merge
     * @return array
     */
    public static function customErrorMessages($merge = [])
    {
        $messages = [];

        return array_merge($messages, $merge);
    }

    /*
    |--------------------------------------------------------------------------
    | Execute validation on module events
    |--------------------------------------------------------------------------
    |
    | Check validations on saving, creating, updating, deleting and restoring
    */

    /**
     * Run validations for saving. This should be common for both creating and updating.
     *
     * @param $loremIpsum \App\Mainframe\Modules\Superheroes\LoremIpsum
     * @return $this
     */
    public function saving($loremIpsum)
    {
        parent::saving($loremIpsum);
        /*
        |--------------------------------------------------------------------------
        | Call validation functions one by one.
        |--------------------------------------------------------------------------
        |
        | A list of functions that will be called sequentially to validate the model
        */
        $this->nameIsNotJoker($loremIpsum);
        // $this->valueIsNotPrime($loremIpsum);
        // $this->hasEnoughGunsToFight($loremIpsum);
        // $this->heroIsNotInHospital($loremIpsum);

        return $this;
    }

    // /**
    //  * Creating validation
    //  *
    //  * @param $loremIpsum \App\Mainframe\Modules\Superheroes\LoremIpsum
    //  * @return \App\Mainframe\Features\Modular\Validator\ModelValidator|\App\Mainframe\Modules\Settings\SettingValidator
    //  */
    // public function creating($loremIpsum)
    // {
    //     return parent::creating($loremIpsum); // TODO: Change the autogenerated stub
    // }
    //
    // /**
    //  * Updating validation
    //  *
    //  * @param $loremIpsum \App\Mainframe\Modules\Superheroes\LoremIpsum
    //  * @return \App\Mainframe\Features\Modular\Validator\ModelValidator|\App\Mainframe\Modules\Settings\SettingValidator
    //  */
    // public function updating($loremIpsum)
    // {
    //     return parent::updating($loremIpsum); // TODO: Change the autogenerated stub
    // }
    //
    // /**
    //  *  Deleting validation
    //  *
    //  * @param $loremIpsum \App\Mainframe\Modules\Superheroes\LoremIpsum
    //  * @return \App\Mainframe\Features\Modular\Validator\ModelValidator|\App\Mainframe\Modules\Settings\SettingValidator
    //  */
    // public function deleting($loremIpsum)
    // {
    //     return parent::deleting($loremIpsum); // TODO: Change the autogenerated stub
    // }
    //
    // /**
    //  * Restoring validation
    //  *
    //  * @param $loremIpsum \App\Mainframe\Modules\Superheroes\LoremIpsum
    //  * @return \App\Mainframe\Features\Modular\Validator\ModelValidator|\App\Mainframe\Modules\Settings\SettingValidator
    //  */
    // public function restoring($loremIpsum)
    // {
    //     return parent::restoring($loremIpsum); // TODO: Change the autogenerated stub
    // }

    /*
    |--------------------------------------------------------------------------
    | Validation helper functions
    |--------------------------------------------------------------------------
    |
    | All validation must be checked through some function. All validation
    | functions are listed below.
    */

    /**
     * Validate the name. Name should not be 'Joker'
     *
     * @param $loremIpsum \App\Mainframe\Modules\Superheroes\LoremIpsum
     * @return $this
     */
    private function nameIsNotJoker($loremIpsum)
    {
        if ($loremIpsum->name === 'Joker') {
            $this->fieldError('name', "Name can not be Joker");
        }

        return $this;
    }
}