<?php

namespace App\Mainframe\Modules\MfProjects;

use App\Mainframe\Features\Modular\Validator\ModelProcessor;

class MfProjectProcessor extends ModelProcessor
{
    /*
    |--------------------------------------------------------------------------
    | Fill model .
    |--------------------------------------------------------------------------
    |
    | Sometimes you need to automatically fill some fields of a model based
    | on known logic. For example: if you can take first_name and last_name
    | of an user and auto fill full_name.
    */

    /**
     * Fill the model with values
     *
     * @param  \App\Mainframe\Modules\MfProjects\MfProject  $mfProject
     * @return $this
     */
    public function fill($mfProject)
    {
        parent::fill($mfProject);

        // $mfProject->name = 'Lorem Ipsum';

        return $this;
    }

    /*
    |--------------------------------------------------------------------------
    | Rules.
    |--------------------------------------------------------------------------
    |
    | Write the laravel validation rules
    */

    /**
     * Validation rules.
     *
     * @param  \App\Mainframe\Modules\MfProjects\MfProject  $mfProject
     * @param  array  $merge
     * @return array
     */
    public static function rules($mfProject, $merge = [])
    {
        $rules = [
            'name' => 'required|between:1,255|unique:mf_projects,name,'.(isset($mfProject->id) ? (string) $mfProject->id : 'null').',id,deleted_at,NULL',
            'is_active' => 'in:1,0',
        ];

        return array_merge($rules, $merge);
    }

    /**
     * Custom error messages.
     *
     * @param  array  $merge
     * @return array
     */
    public static function customErrorMessages($merge = [])
    {
        $messages = [];

        return array_merge($messages, $merge);
    }

    /*
    |--------------------------------------------------------------------------
    | Execute validation on module events
    |--------------------------------------------------------------------------
    |
    | Check validations on saving, creating, updating, deleting and restoring
    */

    /**
     * Run validations for saving. This should be common for both creating and updating.
     *
     * @param $mfProject \App\Mainframe\Modules\Superheroes\MfProject
     * @return $this
     */
    public function saving($mfProject)
    {
        parent::saving($mfProject);
        /*
        |--------------------------------------------------------------------------
        | Call validation functions one by one.
        |--------------------------------------------------------------------------
        |
        | A list of functions that will be called sequentially to validate the model
        */
        $this->nameIsNotJoker($mfProject);
        // $this->valueIsNotPrime($mfProject);
        // $this->hasEnoughGunsToFight($mfProject);
        // $this->heroIsNotInHospital($mfProject);

        return $this;
    }

    // /**
    //  * Creating validation
    //  *
    //  * @param $mfProject \App\Mainframe\Modules\Superheroes\MfProject
    //  * @return \App\Mainframe\Features\Modular\Validator\ModelValidator|\App\Mainframe\Modules\Settings\SettingValidator
    //  */
    // public function creating($mfProject)
    // {
    //     return parent::creating($mfProject); // TODO: Change the autogenerated stub
    // }
    //
    // /**
    //  * Updating validation
    //  *
    //  * @param $mfProject \App\Mainframe\Modules\Superheroes\MfProject
    //  * @return \App\Mainframe\Features\Modular\Validator\ModelValidator|\App\Mainframe\Modules\Settings\SettingValidator
    //  */
    // public function updating($mfProject)
    // {
    //     return parent::updating($mfProject); // TODO: Change the autogenerated stub
    // }
    //
    // /**
    //  *  Deleting validation
    //  *
    //  * @param $mfProject \App\Mainframe\Modules\Superheroes\MfProject
    //  * @return \App\Mainframe\Features\Modular\Validator\ModelValidator|\App\Mainframe\Modules\Settings\SettingValidator
    //  */
    // public function deleting($mfProject)
    // {
    //     return parent::deleting($mfProject); // TODO: Change the autogenerated stub
    // }
    //
    // /**
    //  * Restoring validation
    //  *
    //  * @param $mfProject \App\Mainframe\Modules\Superheroes\MfProject
    //  * @return \App\Mainframe\Features\Modular\Validator\ModelValidator|\App\Mainframe\Modules\Settings\SettingValidator
    //  */
    // public function restoring($mfProject)
    // {
    //     return parent::restoring($mfProject); // TODO: Change the autogenerated stub
    // }

    /*
    |--------------------------------------------------------------------------
    | Validation helper functions
    |--------------------------------------------------------------------------
    |
    | All validation must be checked through some function. All validation
    | functions are listed below.
    */

    /**
     * Validate the name. Name should not be 'Joker'
     *
     * @param $mfProject \App\Mainframe\Modules\Superheroes\MfProject
     * @return $this
     */
    private function nameIsNotJoker($mfProject)
    {
        if ($mfProject->name === 'Joker') {
            $this->addfieldError('name', "Name can not be Joker");
        }

        return $this;
    }
}