<?php

namespace App\Mainframe\Modules\ProductThemes;

use App\Mainframe\Features\Modular\Validator\ModelProcessor;

class ProductThemeProcessor extends ModelProcessor
{
    /*
    |--------------------------------------------------------------------------
    | Fill model .
    |--------------------------------------------------------------------------
    |
    | Sometimes you need to automatically fill some fields of a model based
    | on known logic. For example: if you can take first_name and last_name
    | of an user and auto fill full_name.
    */

    /**
     * Fill the model with values
     *
     * @param  \App\Mainframe\Modules\ProductThemes\ProductTheme  $productTheme
     * @return $this
     */
    public function fill($productTheme)
    {
        parent::fill($productTheme);

        // $productTheme->name = 'Lorem Ipsum';

        return $this;
    }

    /*
    |--------------------------------------------------------------------------
    | Rules.
    |--------------------------------------------------------------------------
    |
    | Write the laravel validation rules
    */

    /**
     * Validation rules.
     *
     * @param  \App\Mainframe\Modules\ProductThemes\ProductTheme  $productTheme
     * @param  array  $merge
     * @return array
     */
    public static function rules($productTheme, $merge = [])
    {
        $rules = [
            'name' => 'required|between:1,255|unique:product_themes,name,'.(isset($productTheme->id) ? (string) $productTheme->id : 'null').',id,deleted_at,NULL',
            'is_active' => 'in:1,0',
        ];

        return array_merge($rules, $merge);
    }

    /**
     * Custom error messages.
     *
     * @param  array  $merge
     * @return array
     */
    public static function customErrorMessages($merge = [])
    {
        $messages = [];

        return array_merge($messages, $merge);
    }

    /*
    |--------------------------------------------------------------------------
    | Execute validation on module events
    |--------------------------------------------------------------------------
    |
    | Check validations on saving, creating, updating, deleting and restoring
    */

    /**
     * Run validations for saving. This should be common for both creating and updating.
     *
     * @param $productTheme \App\Mainframe\Modules\Superheroes\ProductTheme
     * @return $this
     */
    public function saving($productTheme)
    {
        parent::saving($productTheme);
        /*
        |--------------------------------------------------------------------------
        | Call validation functions one by one.
        |--------------------------------------------------------------------------
        |
        | A list of functions that will be called sequentially to validate the model
        */
        $this->nameIsNotJoker($productTheme);
        // $this->valueIsNotPrime($productTheme);
        // $this->hasEnoughGunsToFight($productTheme);
        // $this->heroIsNotInHospital($productTheme);

        return $this;
    }

    // /**
    //  * Creating validation
    //  *
    //  * @param $productTheme \App\Mainframe\Modules\Superheroes\ProductTheme
    //  * @return \App\Mainframe\Features\Modular\Validator\ModelValidator|\App\Mainframe\Modules\Settings\SettingValidator
    //  */
    // public function creating($productTheme)
    // {
    //     return parent::creating($productTheme); // TODO: Change the autogenerated stub
    // }
    //
    // /**
    //  * Updating validation
    //  *
    //  * @param $productTheme \App\Mainframe\Modules\Superheroes\ProductTheme
    //  * @return \App\Mainframe\Features\Modular\Validator\ModelValidator|\App\Mainframe\Modules\Settings\SettingValidator
    //  */
    // public function updating($productTheme)
    // {
    //     return parent::updating($productTheme); // TODO: Change the autogenerated stub
    // }
    //
    // /**
    //  *  Deleting validation
    //  *
    //  * @param $productTheme \App\Mainframe\Modules\Superheroes\ProductTheme
    //  * @return \App\Mainframe\Features\Modular\Validator\ModelValidator|\App\Mainframe\Modules\Settings\SettingValidator
    //  */
    // public function deleting($productTheme)
    // {
    //     return parent::deleting($productTheme); // TODO: Change the autogenerated stub
    // }
    //
    // /**
    //  * Restoring validation
    //  *
    //  * @param $productTheme \App\Mainframe\Modules\Superheroes\ProductTheme
    //  * @return \App\Mainframe\Features\Modular\Validator\ModelValidator|\App\Mainframe\Modules\Settings\SettingValidator
    //  */
    // public function restoring($productTheme)
    // {
    //     return parent::restoring($productTheme); // TODO: Change the autogenerated stub
    // }

    /*
    |--------------------------------------------------------------------------
    | Validation helper functions
    |--------------------------------------------------------------------------
    |
    | All validation must be checked through some function. All validation
    | functions are listed below.
    */

    /**
     * Validate the name. Name should not be 'Joker'
     *
     * @param $productTheme \App\Mainframe\Modules\Superheroes\ProductTheme
     * @return $this
     */
    private function nameIsNotJoker($productTheme)
    {
        if ($productTheme->name === 'Joker') {
            $this->addfieldError('name', "Name can not be Joker");
        }

        return $this;
    }
}